[2016-06-21 13:10:33] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused" at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2016-06-21 13:10:33] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103) {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2016-06-21 13:15:06] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)" at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2016-06-21 13:15:06] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103) {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2016-06-21 13:17:23] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)" at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2016-06-21 13:17:23] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103) {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2016-06-21 13:22:03] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused" at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2016-06-21 13:22:03] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103) {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2016-06-21 13:26:26] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)" at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2016-06-21 13:26:26] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103) {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /Users/mavillaz/TournamentManager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2016-06-21 13:26:37] request.INFO: Matched route "api_get". {"route_parameters":{"_controller":"CoreBundle\\Controller\\DefaultController::getAction","_format":"json","_route":"api_get"},"request_uri":"http://localhost/TournamentManager/web/app_dev.php/"} []
[2016-06-21 13:26:37] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-21 13:26:37] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /Users/mavillaz/TournamentManager/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:70)"} []
[2016-06-21 13:26:37] security.DEBUG: Calling Authentication entry point. [] []
[2016-06-21 13:26:57] request.INFO: Matched route "api_get". {"route_parameters":{"_controller":"CoreBundle\\Controller\\DefaultController::getAction","_format":"json","_route":"api_get"},"request_uri":"http://localhost/TournamentManager/web/app_dev.php/"} []
[2016-06-21 13:26:57] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-21 13:26:57] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /Users/mavillaz/TournamentManager/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:70)"} []
[2016-06-21 13:26:57] security.DEBUG: Calling Authentication entry point. [] []
[2016-06-21 13:30:13] request.INFO: Matched route "api_post_account". {"route_parameters":{"_controller":"UserBundle\\Controller\\AccountController::postAction","_format":"json","_route":"api_post_account"},"request_uri":"http://localhost/tournamentmanager/web/app_dev.php/accounts"} []
[2016-06-21 13:30:13] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Public key "/Users/mavillaz/tournamentmanager/app/var/jwt/public.pem" does not exist or is not readable. Did you correctly set the "lexik_jwt_authentication.public_key_path" parameter?" at /Users/mavillaz/tournamentmanager/vendor/lexik/jwt-authentication-bundle/Lexik/Bundle/JWTAuthenticationBundle/Services/OpenSSLKeyLoader.php line 65 {"exception":"[object] (RuntimeException(code: 0): Public key \"/Users/mavillaz/tournamentmanager/app/var/jwt/public.pem\" does not exist or is not readable. Did you correctly set the \"lexik_jwt_authentication.public_key_path\" parameter? at /Users/mavillaz/tournamentmanager/vendor/lexik/jwt-authentication-bundle/Lexik/Bundle/JWTAuthenticationBundle/Services/OpenSSLKeyLoader.php:65)"} []
[2016-06-21 13:30:54] request.INFO: Matched route "api_post_account". {"route_parameters":{"_controller":"UserBundle\\Controller\\AccountController::postAction","_format":"json","_route":"api_post_account"},"request_uri":"http://localhost/tournamentmanager/web/app_dev.php/accounts"} []
[2016-06-21 13:30:54] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Public key "/Users/mavillaz/tournamentmanager/app/var/jwt/public.pem" does not exist or is not readable. Did you correctly set the "lexik_jwt_authentication.public_key_path" parameter?" at /Users/mavillaz/tournamentmanager/vendor/lexik/jwt-authentication-bundle/Lexik/Bundle/JWTAuthenticationBundle/Services/OpenSSLKeyLoader.php line 65 {"exception":"[object] (RuntimeException(code: 0): Public key \"/Users/mavillaz/tournamentmanager/app/var/jwt/public.pem\" does not exist or is not readable. Did you correctly set the \"lexik_jwt_authentication.public_key_path\" parameter? at /Users/mavillaz/tournamentmanager/vendor/lexik/jwt-authentication-bundle/Lexik/Bundle/JWTAuthenticationBundle/Services/OpenSSLKeyLoader.php:65)"} []
[2016-06-21 13:31:06] request.INFO: Matched route "api_post_account". {"route_parameters":{"_controller":"UserBundle\\Controller\\AccountController::postAction","_format":"json","_route":"api_post_account"},"request_uri":"http://localhost/tournamentmanager/web/app_dev.php/accounts"} []
[2016-06-21 13:31:06] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Public key "/Users/mavillaz/tournamentmanager/app/var/jwt/public.pem" does not exist or is not readable. Did you correctly set the "lexik_jwt_authentication.public_key_path" parameter?" at /Users/mavillaz/tournamentmanager/vendor/lexik/jwt-authentication-bundle/Lexik/Bundle/JWTAuthenticationBundle/Services/OpenSSLKeyLoader.php line 65 {"exception":"[object] (RuntimeException(code: 0): Public key \"/Users/mavillaz/tournamentmanager/app/var/jwt/public.pem\" does not exist or is not readable. Did you correctly set the \"lexik_jwt_authentication.public_key_path\" parameter? at /Users/mavillaz/tournamentmanager/vendor/lexik/jwt-authentication-bundle/Lexik/Bundle/JWTAuthenticationBundle/Services/OpenSSLKeyLoader.php:65)"} []
[2016-06-21 13:31:07] request.INFO: Matched route "api_post_account". {"route_parameters":{"_controller":"UserBundle\\Controller\\AccountController::postAction","_format":"json","_route":"api_post_account"},"request_uri":"http://localhost/tournamentmanager/web/app_dev.php/accounts"} []
[2016-06-21 13:31:07] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Public key "/Users/mavillaz/tournamentmanager/app/var/jwt/public.pem" does not exist or is not readable. Did you correctly set the "lexik_jwt_authentication.public_key_path" parameter?" at /Users/mavillaz/tournamentmanager/vendor/lexik/jwt-authentication-bundle/Lexik/Bundle/JWTAuthenticationBundle/Services/OpenSSLKeyLoader.php line 65 {"exception":"[object] (RuntimeException(code: 0): Public key \"/Users/mavillaz/tournamentmanager/app/var/jwt/public.pem\" does not exist or is not readable. Did you correctly set the \"lexik_jwt_authentication.public_key_path\" parameter? at /Users/mavillaz/tournamentmanager/vendor/lexik/jwt-authentication-bundle/Lexik/Bundle/JWTAuthenticationBundle/Services/OpenSSLKeyLoader.php:65)"} []
[2016-06-21 13:31:59] request.INFO: Matched route "api_post_account". {"route_parameters":{"_controller":"UserBundle\\Controller\\AccountController::postAction","_format":"json","_route":"api_post_account"},"request_uri":"http://localhost/tournamentmanager/web/app_dev.php/accounts"} []
[2016-06-21 13:32:12] request.INFO: Matched route "api_post_account". {"route_parameters":{"_controller":"UserBundle\\Controller\\AccountController::postAction","_format":"json","_route":"api_post_account"},"request_uri":"http://localhost/tournamentmanager/web/app_dev.php/accounts"} []
[2016-06-21 13:32:12] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-21 13:32:12] request.ERROR: Uncaught PHP Exception FOS\RestBundle\Exception\InvalidParameterException: "Parameter "password" of value "" violated a constraint "Cette valeur ne doit pas être nulle."" at /Users/mavillaz/tournamentmanager/vendor/friendsofsymfony/rest-bundle/Exception/InvalidParameterException.php line 66 {"exception":"[object] (FOS\\RestBundle\\Exception\\InvalidParameterException(code: 0): Parameter \"password\" of value \"\" violated a constraint \"Cette valeur ne doit pas être nulle.\" at /Users/mavillaz/tournamentmanager/vendor/friendsofsymfony/rest-bundle/Exception/InvalidParameterException.php:66)"} []
[2016-06-21 13:34:16] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\Mapping\MappingException: "The target-entity CoreBundle\Entity\Promise cannot be found in 'UserBundle\Entity\Account#projectPromise'." at /Users/mavillaz/tournamentmanager/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php line 762 {"exception":"[object] (Doctrine\\ORM\\Mapping\\MappingException(code: 0): The target-entity CoreBundle\\Entity\\Promise cannot be found in 'UserBundle\\Entity\\Account#projectPromise'. at /Users/mavillaz/tournamentmanager/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php:762)"} []
[2016-06-21 13:34:16] request.CRITICAL: Exception thrown when handling an exception (Doctrine\ORM\Mapping\MappingException: The target-entity CoreBundle\Entity\Promise cannot be found in 'UserBundle\Entity\Account#projectPromise'. at /Users/mavillaz/tournamentmanager/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php line 762) {"exception":"[object] (Doctrine\\ORM\\Mapping\\MappingException(code: 0): The target-entity CoreBundle\\Entity\\Promise cannot be found in 'UserBundle\\Entity\\Account#projectPromise'. at /Users/mavillaz/tournamentmanager/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php:762)"} []
[2016-06-21 13:35:36] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\Mapping\MappingException: "The target-entity CoreBundle\Entity\Promise cannot be found in 'UserBundle\Entity\Account#projectPromise'." at /Users/mavillaz/tournamentmanager/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php line 762 {"exception":"[object] (Doctrine\\ORM\\Mapping\\MappingException(code: 0): The target-entity CoreBundle\\Entity\\Promise cannot be found in 'UserBundle\\Entity\\Account#projectPromise'. at /Users/mavillaz/tournamentmanager/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php:762)"} []
[2016-06-21 13:35:36] request.CRITICAL: Exception thrown when handling an exception (Doctrine\ORM\Mapping\MappingException: The target-entity CoreBundle\Entity\Promise cannot be found in 'UserBundle\Entity\Account#projectPromise'. at /Users/mavillaz/tournamentmanager/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php line 762) {"exception":"[object] (Doctrine\\ORM\\Mapping\\MappingException(code: 0): The target-entity CoreBundle\\Entity\\Promise cannot be found in 'UserBundle\\Entity\\Account#projectPromise'. at /Users/mavillaz/tournamentmanager/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php:762)"} []
[2016-06-21 13:35:58] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\FileLoaderLoadException: "Class could not be determined for Controller identified by "CoreBundle\Controller\DefaultController" in /Users/mavillaz/tournamentmanager/app/config/routing_rest.yml (which is being imported from "/Users/mavillaz/tournamentmanager/app/config/routing.yml")." at /Users/mavillaz/tournamentmanager/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 118 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): Class could not be determined for Controller identified by \"CoreBundle\\Controller\\DefaultController\" in /Users/mavillaz/tournamentmanager/app/config/routing_rest.yml (which is being imported from \"/Users/mavillaz/tournamentmanager/app/config/routing.yml\"). at /Users/mavillaz/tournamentmanager/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php:118, InvalidArgumentException(code: 0): Class could not be determined for Controller identified by \"CoreBundle\\Controller\\DefaultController\". at /Users/mavillaz/tournamentmanager/vendor/friendsofsymfony/rest-bundle/Routing/Loader/RestRouteLoader.php:146)"} []
[2016-06-21 13:38:13] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\FileLoaderLoadException: "Class could not be determined for Controller identified by "CoreBundle\Controller\ProjectController" in /Users/mavillaz/tournamentmanager/app/config/routing_rest.yml (which is being imported from "/Users/mavillaz/tournamentmanager/app/config/routing.yml")." at /Users/mavillaz/tournamentmanager/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 118 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): Class could not be determined for Controller identified by \"CoreBundle\\Controller\\ProjectController\" in /Users/mavillaz/tournamentmanager/app/config/routing_rest.yml (which is being imported from \"/Users/mavillaz/tournamentmanager/app/config/routing.yml\"). at /Users/mavillaz/tournamentmanager/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php:118, InvalidArgumentException(code: 0): Class could not be determined for Controller identified by \"CoreBundle\\Controller\\ProjectController\". at /Users/mavillaz/tournamentmanager/vendor/friendsofsymfony/rest-bundle/Routing/Loader/RestRouteLoader.php:146)"} []
[2016-06-21 13:38:25] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\FileLoaderLoadException: "Warning: Invalid argument supplied for foreach() in /Users/mavillaz/tournamentmanager/app/config/routing_rest.yml (which is being imported from "/Users/mavillaz/tournamentmanager/app/config/routing.yml")." at /Users/mavillaz/tournamentmanager/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 118 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): Warning: Invalid argument supplied for foreach() in /Users/mavillaz/tournamentmanager/app/config/routing_rest.yml (which is being imported from \"/Users/mavillaz/tournamentmanager/app/config/routing.yml\"). at /Users/mavillaz/tournamentmanager/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php:118, Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Warning: Invalid argument supplied for foreach() at /Users/mavillaz/tournamentmanager/vendor/friendsofsymfony/rest-bundle/Routing/Loader/RestYamlCollectionLoader.php:69)"} []
[2016-06-21 13:39:41] request.INFO: Matched route "api_post_account". {"route_parameters":{"_controller":"UserBundle\\Controller\\AccountController::postAction","_format":"json","_route":"api_post_account"},"request_uri":"http://localhost/tournamentmanager/web/app_dev.php/accounts"} []
[2016-06-21 13:39:41] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-21 13:39:41] request.ERROR: Uncaught PHP Exception FOS\RestBundle\Exception\InvalidParameterException: "Parameter "password" of value "" violated a constraint "Cette valeur ne doit pas être nulle."" at /Users/mavillaz/tournamentmanager/vendor/friendsofsymfony/rest-bundle/Exception/InvalidParameterException.php line 66 {"exception":"[object] (FOS\\RestBundle\\Exception\\InvalidParameterException(code: 0): Parameter \"password\" of value \"\" violated a constraint \"Cette valeur ne doit pas être nulle.\" at /Users/mavillaz/tournamentmanager/vendor/friendsofsymfony/rest-bundle/Exception/InvalidParameterException.php:66)"} []
[2016-06-21 13:40:06] request.INFO: Matched route "api_post_account". {"route_parameters":{"_controller":"UserBundle\\Controller\\AccountController::postAction","_format":"json","_route":"api_post_account"},"request_uri":"http://localhost/tournamentmanager/web/app_dev.php/accounts"} []
[2016-06-21 13:40:06] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-21 13:40:06] request.ERROR: Uncaught PHP Exception FOS\RestBundle\Exception\InvalidParameterException: "Parameter "password_confirmation" of value "" violated a constraint "Cette valeur ne doit pas être nulle."" at /Users/mavillaz/tournamentmanager/vendor/friendsofsymfony/rest-bundle/Exception/InvalidParameterException.php line 66 {"exception":"[object] (FOS\\RestBundle\\Exception\\InvalidParameterException(code: 0): Parameter \"password_confirmation\" of value \"\" violated a constraint \"Cette valeur ne doit pas être nulle.\" at /Users/mavillaz/tournamentmanager/vendor/friendsofsymfony/rest-bundle/Exception/InvalidParameterException.php:66)"} []
[2016-06-21 13:40:15] request.INFO: Matched route "api_post_account". {"route_parameters":{"_controller":"UserBundle\\Controller\\AccountController::postAction","_format":"json","_route":"api_post_account"},"request_uri":"http://localhost/tournamentmanager/web/app_dev.php/accounts"} []
[2016-06-21 13:40:15] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-21 13:40:16] translation.WARNING: Translation not found. {"id":"\"%string%\" doesn't valid email","domain":"validators","locale":"fr"} []
[2016-06-21 13:40:16] request.ERROR: Uncaught PHP Exception FOS\RestBundle\Exception\InvalidParameterException: "Parameter "email" of value "" violated a constraint "Cette valeur ne doit pas être nulle." Parameter "email" of value "" violated a constraint """ doesn't valid email"" at /Users/mavillaz/tournamentmanager/vendor/friendsofsymfony/rest-bundle/Exception/InvalidParameterException.php line 66 {"exception":"[object] (FOS\\RestBundle\\Exception\\InvalidParameterException(code: 0): Parameter \"email\" of value \"\" violated a constraint \"Cette valeur ne doit pas être nulle.\"\nParameter \"email\" of value \"\" violated a constraint \"\"\" doesn't valid email\" at /Users/mavillaz/tournamentmanager/vendor/friendsofsymfony/rest-bundle/Exception/InvalidParameterException.php:66)"} []
[2016-06-21 13:40:34] request.INFO: Matched route "api_post_account". {"route_parameters":{"_controller":"UserBundle\\Controller\\AccountController::postAction","_format":"json","_route":"api_post_account"},"request_uri":"http://localhost/tournamentmanager/web/app_dev.php/accounts"} []
[2016-06-21 13:40:34] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-21 13:40:35] doctrine.DEBUG: SELECT t0.username AS username_1, t0.username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6, t0.password AS password_7, t0.last_login AS last_login_8, t0.locked AS locked_9, t0.expired AS expired_10, t0.expires_at AS expires_at_11, t0.confirmation_token AS confirmation_token_12, t0.password_requested_at AS password_requested_at_13, t0.roles AS roles_14, t0.credentials_expired AS credentials_expired_15, t0.credentials_expire_at AS credentials_expire_at_16, t0.id AS id_17, t0.address AS address_18, t0.city AS city_19, t0.country AS country_20, t0.region AS region_21, t0.phone AS phone_22, t0.img AS img_23, t0.created_at AS created_at_24, t0.updated_at AS updated_at_25 FROM account t0 WHERE t0.username = ? ["remi.mavillaz@live.fr"] []
[2016-06-21 13:40:35] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT t0.username AS username_1, t0.username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6, t0.password AS password_7, t0.last_login AS last_login_8, t0.locked AS locked_9, t0.expired AS expired_10, t0.expires_at AS expires_at_11, t0.confirmation_token AS confirmation_token_12, t0.password_requested_at AS password_requested_at_13, t0.roles AS roles_14, t0.credentials_expired AS credentials_expired_15, t0.credentials_expire_at AS credentials_expire_at_16, t0.id AS id_17, t0.address AS address_18, t0.city AS city_19, t0.country AS country_20, t0.region AS region_21, t0.phone AS phone_22, t0.img AS img_23, t0.created_at AS created_at_24, t0.updated_at AS updated_at_25 FROM account t0 WHERE t0.username = ?' with params ["remi.mavillaz@live.fr"]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tournament-manager.account' doesn't exist" at /Users/mavillaz/tournamentmanager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.username AS username_1, t0.username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6, t0.password AS password_7, t0.last_login AS last_login_8, t0.locked AS locked_9, t0.expired AS expired_10, t0.expires_at AS expires_at_11, t0.confirmation_token AS confirmation_token_12, t0.password_requested_at AS password_requested_at_13, t0.roles AS roles_14, t0.credentials_expired AS credentials_expired_15, t0.credentials_expire_at AS credentials_expire_at_16, t0.id AS id_17, t0.address AS address_18, t0.city AS city_19, t0.country AS country_20, t0.region AS region_21, t0.phone AS phone_22, t0.img AS img_23, t0.created_at AS created_at_24, t0.updated_at AS updated_at_25 FROM account t0 WHERE t0.username = ?' with params [\"remi.mavillaz@live.fr\"]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'tournament-manager.account' doesn't exist at /Users/mavillaz/tournamentmanager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tournament-manager.account' doesn't exist at /Users/mavillaz/tournamentmanager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tournament-manager.account' doesn't exist at /Users/mavillaz/tournamentmanager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
